server:
  port: 8083

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbname: order_service

jwt:
  secret: "my_secret_key"
  expire: 7200

services:
  user_service: "localhost:8081"
  product_service: "localhost:8082"
